// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YonetimPaneli.Models;

#nullable disable

namespace yonetimpaneli.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260714090000_GorevPlanlamaAlanlariEkle")]
    partial class GorevPlanlamaAlanlariEkle
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618

            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YonetimPaneli.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi").HasColumnType("bit");
                    b.Property<string>("Ad").HasColumnType("nvarchar(max)");
                    b.Property<int?>("DepartmanId").HasColumnType("int");
                    b.Property<string>("Email").HasColumnType("nvarchar(max)");
                    b.Property<int>("KidemSeviyesi").HasColumnType("int");
                    b.Property<int>("OrganizasyonRolu").HasColumnType("int");
                    b.Property<string>("Password").HasColumnType("nvarchar(max)");
                    b.Property<string>("Role").HasColumnType("nvarchar(max)");
                    b.Property<string>("Soyad").HasColumnType("nvarchar(max)");
                    b.Property<int?>("UnvanId").HasColumnType("int");
                    b.Property<int?>("YoneticiId").HasColumnType("int");

                    b.HasKey("Id");
                    b.HasIndex("DepartmanId");
                    b.HasIndex("UnvanId");
                    b.HasIndex("YoneticiId");
                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Departman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Ad").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                    b.Property<int?>("UstDepartmanId").HasColumnType("int");

                    b.HasKey("Id");
                    b.HasIndex("UstDepartmanId");
                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Gorev", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("BaslangicTarihi").HasColumnType("datetime2");
                    b.Property<int?>("AtananKullaniciId").HasColumnType("int");
                    b.Property<string>("AtananKullaniciAdi").HasColumnType("nvarchar(max)");
                    b.Property<string>("AtananUserId").HasColumnType("nvarchar(max)");
                    b.Property<string>("Baslik").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Durum").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Oncelik").HasColumnType("int");
                    b.Property<int?>("OlusturanKullaniciId").HasColumnType("int");
                    b.Property<DateTime>("OlusturulmaTarihi").HasColumnType("datetime2");
                    b.Property<string>("ResimYolu").HasColumnType("nvarchar(max)");
                    b.Property<DateTime?>("SonTarih").HasColumnType("datetime2");
                    b.Property<DateTime?>("TamamlanmaTarihi").HasColumnType("datetime2");

                    b.HasKey("Id");
                    b.HasIndex("AtananKullaniciId");
                    b.HasIndex("OlusturanKullaniciId");
                    b.HasIndex("Oncelik");
                    b.HasIndex("SonTarih");
                    b.ToTable("Gorevler");
                });


            modelBuilder.Entity("YonetimPaneli.Models.GorevAktivite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EskiDeger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<string>("IslemTuru")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("YeniDeger")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GorevAktiviteleri");
                });

            modelBuilder.Entity("YonetimPaneli.Models.GorevYorum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DuzenlenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("GorevId")
                        .HasColumnType("int");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SilindiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GorevId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("GorevYorumlari");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Unvan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama").HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<string>("Ad").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");

                    b.HasKey("Id");
                    b.ToTable("Unvanlar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.AppUser", b =>
                {
                    b.HasOne("YonetimPaneli.Models.Departman", "Departman")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("DepartmanId");

                    b.HasOne("YonetimPaneli.Models.Unvan", "Unvan")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("UnvanId");

                    b.HasOne("YonetimPaneli.Models.AppUser", "Yonetici")
                        .WithMany("Astlar")
                        .HasForeignKey("YoneticiId");

                    b.Navigation("Departman");
                    b.Navigation("Unvan");
                    b.Navigation("Yonetici");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Departman", b =>
                {
                    b.HasOne("YonetimPaneli.Models.Departman", "UstDepartman")
                        .WithMany("AltDepartmanlar")
                        .HasForeignKey("UstDepartmanId");

                    b.Navigation("UstDepartman");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Gorev", b =>
                {
                    b.HasOne("YonetimPaneli.Models.AppUser", "AtananKullanici")
                        .WithMany()
                        .HasForeignKey("AtananKullaniciId");

                    b.HasOne("YonetimPaneli.Models.AppUser", "OlusturanKullanici")
                        .WithMany()
                        .HasForeignKey("OlusturanKullaniciId");

                    b.Navigation("AtananKullanici");
                    b.Navigation("OlusturanKullanici");
                });


            modelBuilder.Entity("YonetimPaneli.Models.GorevAktivite", b =>
                {
                    b.HasOne("YonetimPaneli.Models.Gorev", "Gorev")
                        .WithMany("Aktiviteler")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YonetimPaneli.Models.AppUser", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId");

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YonetimPaneli.Models.GorevYorum", b =>
                {
                    b.HasOne("YonetimPaneli.Models.Gorev", "Gorev")
                        .WithMany("Yorumlar")
                        .HasForeignKey("GorevId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YonetimPaneli.Models.AppUser", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Gorev");

                    b.Navigation("Kullanici");
                });


            modelBuilder.Entity("YonetimPaneli.Models.Gorev", b =>
                {
                    b.Navigation("Aktiviteler");

                    b.Navigation("Yorumlar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.AppUser", b =>
                {
                    b.Navigation("Astlar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Departman", b =>
                {
                    b.Navigation("AltDepartmanlar");
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("YonetimPaneli.Models.Unvan", b =>
                {
                    b.Navigation("Kullanicilar");
                });

#pragma warning restore 612, 618
        }
    }
}
